[phases.setup]
nixPkgs = ["nodejs-20_x", "openssl"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build",
  "mkdir -p /app/uploads"
]

[start]
cmd = "npm start"

[env]
UPLOAD_DIR = "/app/uploads"
